#!/bin/bash
## find root directory
dir_name_rel=$(dirname $0)
dir_name=$(cd $(dirname $dir_name_rel); pwd -P)/$(basename $dir_name_rel)
echo "source directory = $dir_name"

## vim
rm -rf ~/.vim
rm -rf ~/.vimrc

ln -s ${dir_name}/vim   ~/.vim
ln -s ${dir_name}/vimrc ~/.vimrc

git submodule update --init --recursive --progress

## emacs
if [ -e myelpa.zip ]; then
    echo "Info   : MYELPA available already! skip download/unzip."
else
    curl https://codeload.github.com/redguardtoo/myelpa/zip/stable -o myelpa.zip
    unzip myelpa.zip
fi

if ! [ -e ditaa0_9.zip ]; then
    curl https://jaist.dl.sourceforge.net/project/ditaa/ditaa/0.9/ditaa0_9.zip -o ditaa0_9.zip
    unzip -d ditaa ditaa0_9.zip
else
    echo "Info   : DITAA available already! skip download/unzip."
fi

if [ -e ~/.emacs.d ]; then
    mv ~/.emacs.d ~/.emacs.d.old
fi
ln -s ${dir_name}/emacs.d ~/.emacs.d

## git
if ! [ -e ~/.gitconfig ]; then
    ln -s ${dir_name}/gitconfig ~/.gitconfig
else
    echo "Warning: .gitconif exist!"
fi

## bashrc
if ! [ -e ~/.bashrc ]; then
    ln -s ${dir_name}/bashrc ~/.bashrc
    ln -s ${dir_name}/bash_functions ~/.bash_functions
else
    echo "Warning: .bashrc exist!"
fi

## tmux
if ! [ -e ~/.tmux.conf]; then
    ln -s ${dir_name}/tmux.conf ~/.tmux.conf
else
    echo "Warning: .tmux.conf exist!"
fi

