" if vim version is less than 800, there's no native package manager.
" Use pathogen. It's simple and effective.
if v:version < 800
    call pathogen#infect()
    call pathogen#helptags()
endif

syntax on
filetype plugin indent on
filetype plugin on

" powerline is about to deprecate py2.7 support
"set rtp+=/usr/lib/python2.7/site-packages/powerline/bindings/vim/

" terminal 256
let g:solarized_termcolors=256
set t_Co=256
set bg=dark
if (has("gui_running"))
    "colorscheme desert
    "colorscheme molokai 
    colorscheme solarized
else
    "colorscheme desert256
    "colorscheme molokai 
    colorscheme solarized
endif

""
if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 12
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h14
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  endif
endif

set tags=./.tags;,.tags
set nocst

let g:verilog_syntax_fold_lst="function,task,block,comment,define,instance"
au FileType verilog_systemverilog setlocal foldmethod=syntax

let g:hl_matchit_enable_on_vim_startup = 1

set colorcolumn=80

set cursorcolumn

let g:snipMate = { 'snippet_version' : 1 }
"ActivateAddons vim-snippets snipmate

autocmd FileType verilog_systemverilog setlocal commentstring=\/\/\ %s

"" Regular
set wildmenu
set nu
set incsearch
set hlsearch
set vb
set sw=4
set ts=4
set et
set ai
set si
set ic
set magic

set noerrorbells
set novisualbell

set nobackup
set nowb
set noswapfile

" status line
set laststatus=2

" lightline plugin is better option than code below
"function! CurDir()
"    let curdir = substitute( getcwd(),'/home/bruce.li',"~/","g")
"    return curdir
"endfunction
"
"set statusline=
"set statusline+=%-3.3n\                         " Buffer
"set statusline+=%f\                             " filename
"set statusline+=%h%m%r%w                        " flags
"set statusline+=\[%{strlen(&ft)?&ft:'none'},    " File type
"set statusline+=%{&encoding},                   " Encoding
"set statusline+=%{&fileformat}]\ \              " Fileformat
""set statusline+=CWD:\ %r%{CurDir()}%h
"set statusline+=%=                              " Right align
"set statusline+=0x%-8B\                         " Current char
"set statusline+=%-14.(%l,%c%V%)\ %<%P           " offset

" mapping
let mapleader=","

map <leader>ls :ls<cr>

map <C-j> 5j
map <C-k> 5k

" maybe helpful command
" set formatoptions-=r
" set formatoptions-=o
"

" XML folding
let g:xml_syntax_folding=1
au FileType xml setlocal foldmethod=syntax

"
"set enc=utf-8

"
set diffopt=filler,iwhite

"indent_guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=black
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=black
